@url = http://localhost:8080
@jwt = 

### CREATE ACCOUNT

POST {{url}}/api/appUsers HTTP/1.1
Content-Type: application/json

{
    "username": "skylar",
    "password": "P@ssw0rd!"
}

### AUTHENTICATE USER

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "skylar",
    "password": "P@ssw0rd!"
}

### GET ALL USERS

GET {{url}}/api/appUsers HTTP/1.1

### CREATE BOOK

POST {{url}}/api/books HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "title": "War and Peace",
    "language": "English",
    "pages": 1296,
    "author": "Leo Tolstoy",
    "appUserId": "1"
}

### CREATE READING LOG

POST {{url}}/api/readingLogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "bookId": "24",
    "finish": "2022-12-17",
    "start": "2022-12-14"
}
